theme: jekyll-theme-minimal
title: Corso di alfabetizzazione su Python

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/

# Turn on built-in syntax highlighting.
highlighter: rouge
